<a href="https://colab.research.google.com/github/Mayank-004/VC-Industry-Predictive-analysis/blob/main/VC_Target_MOIC_KMEANS_CLUSTERING.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Importing the libraries

In [431]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sn
from sklearn.preprocessing import OrdinalEncoder

## Importing the dataset

In [432]:
url1 = 'https://raw.githubusercontent.com/Mayank-004/Project-in-python/main/VC_Exits.csv'
dataset1 = pd.read_csv(url1, error_bad_lines=False)

#url2 = 'https://raw.githubusercontent.com/Mayank-004/Project-in-python/main/VCExit2.csv'
#dataset2 = pd.read_csv(url2, error_bad_lines=False)

url3 = 'https://raw.githubusercontent.com/Mayank-004/Project-in-python/main/VCData2.csv'
dataset3 = pd.read_csv(url3, error_bad_lines=False)

dataset = pd.merge(dataset1,dataset3,left_on=["Company PBID"],right_on=["Company ID"])



dataset

    Company PBID Exit Date  ... Company Country Year Founded
0      155748-70  11/15/17  ...   United States       2014.0
1      155748-70  11/15/17  ...   United States       2014.0
2      160695-55   1/13/17  ...          Israel       2015.0
3       81857-08   3/18/19  ...   United States       2013.0
4      168816-52   8/16/17  ...         Belarus       2016.0
..           ...       ...  ...             ...          ...
300    431327-53    8/8/16  ...           China       2001.0
301    431327-53    8/8/16  ...           China       2001.0
302    171924-04   9/21/17  ...           China       2008.0
303     56017-63   4/18/19  ...   United States       2011.0
304     56017-63   4/18/19  ...   United States       2011.0

[305 rows x 105 columns]

### Filling missing values of Target column MOIC

In [433]:
# target column MOIC is derived by Exit Size divided by Total VC capital raised
dataset['Total VC Capital Raised ($M)***']= dataset['Total VC Capital Raised ($M)***'].str.replace("$","") # removing $ from Total VC capital
dataset['Total VC Capital Raised ($M)***']= dataset['Total VC Capital Raised ($M)***'].str.replace(",","") # removing "," from Total VC capital
dataset.loc[:,'Total VC Capital Raised ($M)***'] = dataset.loc[:,'Total VC Capital Raised ($M)***'].astype(float) # converting Total VC capital to float from string
dataset['Total VC Capital Raised ($M)***']
dataset['Exit Size (millions)']= dataset['Exit Size (millions)'].str.replace("$","") # removing $ from Exit Size
dataset['Exit Size (millions)']= dataset['Exit Size (millions)'].str.replace(",","") # removing "," from Exit Size
dataset.loc[:,'Exit Size (millions)'] = dataset.loc[:,'Exit Size (millions)'].astype(float) # converting Total VC capital to float from string

dataset['MOIC']= dataset['MOIC'].str.replace("x","") # removing $ from MOIC
dataset['MOIC']= dataset['MOIC'].str.replace(",","") # removing ',' from MOIC
dataset.loc[:,'MOIC'] = dataset.loc[:,'MOIC'].astype(float) # converting MOIC to float from string

#dataset=dataset.drop(columns=['Exit Size (millions)','Total VC Capital Raised ($M)***'])
# Drop duplicate columns  

dataset=dataset.drop(columns=['Deal ID','Company ID','Primary Industry Sector','Primary Industry Group','Primary Industry Code','All Industries','Verticals_y','HQ Location','HQ Global Region','HQ Global Sub Region','Company City',		'Company Country'])

# Drop Column intuitively which may not have significant impact
dataset=dataset.drop(columns=['Company PBID','Exit Date','Post Value (millions)','Native Currency of Deal','Keywords','Deal No.','Deal ID.1','Deal Date','Deal Class','Deal Status','CEO PBId'])

In [434]:
# check missing value in dataset
missing = dataset.isna().sum().sort_values(ascending = False)
percent_missing = ((missing / dataset.isnull().count()) * 100).sort_values(ascending = False)
missing_df = pd.concat([missing,percent_missing], axis = 1, keys = ['Total', 'Percent'],sort = False)
missing_df[missing_df['Total'] >= 1]

                                 Total     Percent
Deal Type 3                        305  100.000000
Implied EV                         305  100.000000
Debt Type 3                        305  100.000000
Implied EV/Cash Flow               305  100.000000
Implied EV/Revenue                 305  100.000000
...                                ...         ...
Company Post Code                   28    9.180328
Raised to Date                      24    7.868852
Total VC Capital Raised ($M)***     23    7.540984
Year Founded                         5    1.639344
Financing Status                     1    0.327869

[69 rows x 2 columns]

Drop Column which has missing values more than 5%

---

In [435]:
missing_df = missing_df.reset_index()
over30 = list(missing_df.loc[missing_df['Percent'] >= 5,'index'])
dataset = dataset.drop(over30, axis = 1)

In [436]:
dataset

              Exit Type Last VC Deal Type  ...        Financing Status Year Founded
0    Merger/Acquisition    Early Stage VC  ...             Corporation       2014.0
1    Merger/Acquisition    Early Stage VC  ...  Venture Capital-Backed       2014.0
2    Merger/Acquisition    Early Stage VC  ...  Venture Capital-Backed       2015.0
3    Merger/Acquisition    Early Stage VC  ...  Venture Capital-Backed       2013.0
4    Merger/Acquisition        Seed Round  ...  Venture Capital-Backed       2016.0
..                  ...               ...  ...                     ...          ...
300                 IPO    Later Stage VC  ...  Venture Capital-Backed       2001.0
301                 IPO    Later Stage VC  ...  Venture Capital-Backed       2001.0
302                 IPO         Corporate  ...  Venture Capital-Backed       2008.0
303                 IPO          Series D  ...  Venture Capital-Backed       2011.0
304                 IPO          Series D  ...  Venture Capital-Backed       2011.0

[305 rows x 15 columns]

In [437]:
# calculating total working duration of company


from datetime import date 
todays_date = date.today() 

ts =todays_date.year

dataset['Total duration for Company'] = ts - dataset['Year Founded']

dataset=dataset.drop(columns=['Year Founded'])

dataset['Total duration for Company']

0       7.0
1       7.0
2       6.0
3       8.0
4       5.0
       ...
300    20.0
301    20.0
302    13.0
303    10.0
304    10.0
Name: Total duration for Company, Length: 305, dtype: float64

In [438]:
dataset

              Exit Type  ... Total duration for Company
0    Merger/Acquisition  ...                        7.0
1    Merger/Acquisition  ...                        7.0
2    Merger/Acquisition  ...                        6.0
3    Merger/Acquisition  ...                        8.0
4    Merger/Acquisition  ...                        5.0
..                  ...  ...                        ...
300                 IPO  ...                       20.0
301                 IPO  ...                       20.0
302                 IPO  ...                       13.0
303                 IPO  ...                       10.0
304                 IPO  ...                       10.0

[305 rows x 15 columns]

## Filling Missing Values

In [439]:
# check missing value in df
missing = dataset.isna().sum().sort_values(ascending = False)
percent_missing = ((missing / dataset.isnull().count()) * 100).sort_values(ascending = False)
missing_df = pd.concat([missing,percent_missing], axis = 1, keys = ['Total', 'Percent'],sort = False)
missing_df[missing_df['Total'] >= 1]

                            Total   Percent
Total duration for Company      5  1.639344
Financing Status                1  0.327869

In [440]:
# filling missing values in all other columns with mean 

dataset = dataset.fillna((dataset.mean()))

dataset.dropna(subset = ["Financing Status"], inplace=True)
#dataset.apply(lambda x: x.fillna(x.mean()),axis=0)

## Encoding categorical data

Label Encoding of Categorical Variable

In [441]:
#Encoder
def label_encoder(dataset):

    #Takes in dataset, returns label encoded dataframe and the label encoder models
    dataset_lencoded = dataset.copy(deep=True);
    label_encoders = [None]*dataset.shape[1];

    for i in range(dataset.shape[1]):
        le = LabelEncoder()
        dataset_lencoded.iloc[:,i] = le.fit_transform(dataset_lencoded.iloc[:,i])
        label_encoders[i] = le
    return dataset_lencoded, label_encoders


#Decoder
def label_decoder(dataset_lencoded, label_encoders):

    #Takes in encoded dataframe and list of encoders and returns decoded dataset
    #Label encoder is a list of label encoder models pertaining to each column
    for i in range(dataset_lencoded.shape[1]):
        dataset_lencoded.iloc[:,i] = label_encoders[i].inverse_transform(dataset_lencoded.iloc[:,i])

    return dataset_lencoded #Now it is decoded

In [442]:
dataset,x = label_encoder(dataset)
dataset

     Exit Type  Last VC Deal Type  ...  Financing Status  Total duration for Company
0            2                  1  ...                 2                           3
1            2                  1  ...                 4                           3
2            2                  1  ...                 4                           2
3            2                  1  ...                 4                           4
4            2                  3  ...                 4                           1
..         ...                ...  ...               ...                         ...
300          1                  2  ...                 4                          17
301          1                  2  ...                 4                          17
302          1                  0  ...                 4                          10
303          1                 12  ...                 4                           7
304          1                 12  ...                 4                           7

[304 rows x 15 columns]

### Building Models

In [443]:
 import matplotlib.pyplot as plt
 #from kneed import kneeLocator
 from sklearn.cluster import KMeans
 from sklearn.metrics import silhouette_score
 from sklearn.preprocessing import StandardScaler

In [444]:
kmeans = KMeans(
            init="random",
            n_clusters=3,
            n_init=10,
            max_iter=300,
            random_state=42
  )

In [445]:
kmeans.fit(dataset)

KMeans(algorithm='auto', copy_x=True, init='random', max_iter=300, n_clusters=3,
       n_init=10, n_jobs=None, precompute_distances='auto', random_state=42,
       tol=0.0001, verbose=0)

In [446]:
dataset

     Exit Type  Last VC Deal Type  ...  Financing Status  Total duration for Company
0            2                  1  ...                 2                           3
1            2                  1  ...                 4                           3
2            2                  1  ...                 4                           2
3            2                  1  ...                 4                           4
4            2                  3  ...                 4                           1
..         ...                ...  ...               ...                         ...
300          1                  2  ...                 4                          17
301          1                  2  ...                 4                          17
302          1                  0  ...                 4                          10
303          1                 12  ...                 4                           7
304          1                 12  ...                 4                           7

[304 rows x 15 columns]

In [447]:
kmeans.labels_

array([2, 2, 0, 1, 2, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 2, 2, 2, 0, 0,
       1, 1, 0, 0, 1, 2, 2, 0, 1, 0, 0, 0, 0, 0, 0, 2, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 2, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 2,
       2, 2, 1, 2, 0, 0, 1, 1, 2, 0, 0, 0, 0, 0, 2, 0, 0, 1, 1, 2, 2, 0,
       0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 2, 2, 0, 2, 2, 2, 2, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 2, 2, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 1, 1, 1, 1, 2,
       2, 0, 0, 0, 2, 2, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 2, 2, 2, 2, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 2, 2,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 2, 2, 0, 0, 0, 0, 0, 0,
       2, 2, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0,
       0, 0, 2, 2, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 2, 2, 2, 1, 0, 0], dtype=int32)

In [449]:
label_decoder(dataset,x)

              Exit Type  ... Total duration for Company
0    Merger/Acquisition  ...                        7.0
1    Merger/Acquisition  ...                        7.0
2    Merger/Acquisition  ...                        6.0
3    Merger/Acquisition  ...                        8.0
4    Merger/Acquisition  ...                        5.0
..                  ...  ...                        ...
300                 IPO  ...                       20.0
301                 IPO  ...                       20.0
302                 IPO  ...                       13.0
303                 IPO  ...                       10.0
304                 IPO  ...                       10.0

[304 rows x 15 columns]

In [450]:
dataset[kmeans.labels_==0]

              Exit Type  ... Total duration for Company
2    Merger/Acquisition  ...                        6.0
5    Merger/Acquisition  ...                        9.0
6            Buyout/LBO  ...                       20.0
11   Merger/Acquisition  ...                        8.0
12   Merger/Acquisition  ...                        9.0
..                  ...  ...                        ...
294                 IPO  ...                       17.0
295                 IPO  ...                       17.0
296                 IPO  ...                       17.0
303                 IPO  ...                       10.0
304                 IPO  ...                       10.0

[158 rows x 15 columns]

In [451]:
dataset[kmeans.labels_==1]

              Exit Type  ... Total duration for Company
3    Merger/Acquisition  ...                        8.0
7    Merger/Acquisition  ...                        6.0
8    Merger/Acquisition  ...                        6.0
9    Merger/Acquisition  ...                        6.0
10   Merger/Acquisition  ...                        6.0
..                  ...  ...                        ...
286          Buyout/LBO  ...                       13.0
287          Buyout/LBO  ...                       13.0
297  Merger/Acquisition  ...                       16.0
298  Merger/Acquisition  ...                       16.0
302                 IPO  ...                       13.0

[89 rows x 15 columns]

In [452]:
dataset[kmeans.labels_==2]

              Exit Type  ... Total duration for Company
0    Merger/Acquisition  ...                   7.000000
1    Merger/Acquisition  ...                   7.000000
4    Merger/Acquisition  ...                   5.000000
17   Merger/Acquisition  ...                   6.000000
18   Merger/Acquisition  ...                   6.000000
19   Merger/Acquisition  ...                   6.000000
27   Merger/Acquisition  ...                   9.976667
28   Merger/Acquisition  ...                   9.976667
37   Merger/Acquisition  ...                   9.000000
47   Merger/Acquisition  ...                  12.000000
51   Merger/Acquisition  ...                   9.000000
52   Merger/Acquisition  ...                   9.000000
65   Merger/Acquisition  ...                  10.000000
66   Merger/Acquisition  ...                  10.000000
67   Merger/Acquisition  ...                  10.000000
69   Merger/Acquisition  ...                  12.000000
74   Merger/Acquisition  ...                   6.000000
80           Buyout/LBO  ...                  10.000000
85                  IPO  ...                  12.000000
86                  IPO  ...                  12.000000
98   Merger/Acquisition  ...                  10.000000
99   Merger/Acquisition  ...                  10.000000
101  Merger/Acquisition  ...                   8.000000
102  Merger/Acquisition  ...                   8.000000
103  Merger/Acquisition  ...                   8.000000
104  Merger/Acquisition  ...                   8.000000
120  Merger/Acquisition  ...                   5.000000
121  Merger/Acquisition  ...                   5.000000
122  Merger/Acquisition  ...                   5.000000
169                 IPO  ...                  15.000000
170                 IPO  ...                  15.000000
175  Merger/Acquisition  ...                   9.000000
176  Merger/Acquisition  ...                   9.000000
180  Merger/Acquisition  ...                   7.000000
181  Merger/Acquisition  ...                   7.000000
199  Merger/Acquisition  ...                   9.000000
200                 IPO  ...                  19.000000
201                 IPO  ...                  19.000000
202                 IPO  ...                  19.000000
218                 IPO  ...                  13.000000
219                 IPO  ...                  13.000000
231  Merger/Acquisition  ...                  24.000000
234  Merger/Acquisition  ...                  12.000000
235  Merger/Acquisition  ...                  12.000000
243  Merger/Acquisition  ...                  17.000000
244  Merger/Acquisition  ...                  17.000000
251  Merger/Acquisition  ...                   7.000000
252  Merger/Acquisition  ...                   7.000000
255  Merger/Acquisition  ...                   7.000000
256  Merger/Acquisition  ...                   7.000000
257  Merger/Acquisition  ...                   7.000000
258  Merger/Acquisition  ...                   7.000000
267                 IPO  ...                  12.000000
268                 IPO  ...                  12.000000
299                 IPO  ...                  20.000000
300                 IPO  ...                  20.000000
301                 IPO  ...                  20.000000

[57 rows x 15 columns]